In [1]:
import numpy as np
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [3]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print("Vectorized version: " + str(1000 * (toc - tic)) + "ms")

Vectorized version: 2.06184387207ms


In [4]:
c = 0
tic = time.time()
for i in range(len(a)):
    c += a[i]*b[i]
toc = time.time()

print("For loop version: " + str(1000 * (toc - tic)) + "ms")

For loop version: 930.183172226ms


In [5]:
v = np.random.rand(1000000)
u = np.exp(v)
print("Create a vector u, elements are e.pow(v)" + str(u))

Create a vector u, elements are e.pow(v)[ 2.59330398  1.59845826  2.65186885 ...,  1.0550108   2.55841375
  1.62771969]


In [15]:
###
## Logisting regrassion derivatives
###
## X - matrix R(nx, m)
## z - vector of [z(1), z(2), ... , z(m)]
## z = [z(1), z(2), ... ,z(m)] = wTX + [b, b, ... b], b is a (1,m vector)
m = 10000
nx = 10000
b = 5
J = 0, dw = 0, db = 0
for i in range(1, m):
    z[i] = w.T * X + b
    a[i] = #
    dz = A - Y
    dw = (1/m) * X * dz.T
    db = (1/m) * np.sum(dz)
    w = w - w - a * dw
    b = b - a * db

print(z)

[[ 5.02149597  5.47539282  5.33789066 ...,  5.27958687  5.09633287
   5.48998319]
 [ 5.05356108  5.57208682  5.56337476 ...,  5.267931    5.50983116
   5.76676489]
 [ 5.00875791  5.73315648  5.07080636 ...,  5.06926198  5.69494366
   5.10903854]
 ..., 
 [ 5.63130988  5.00154001  5.11096319 ...,  5.2460426   5.79715635
   5.03868331]
 [ 5.12857278  5.08266877  5.15841508 ...,  5.02527477  5.06114992
   5.20696797]
 [ 5.1815987   5.28103017  5.11659767 ...,  5.05719362  5.75593478
   5.16212189]]


In [19]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
            [1.2, 104.0, 52.0, 8.0],
            [1.8, 135.0, 99.0, 0.9]])
print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [20]:
cal = A.sum(axis=0)
print(cal)

[  59.   239.   155.4   76.9]


In [28]:
percentage = 100 * A / cal.reshape(1, 4)
print(percentage)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [30]:
print(np.array([1, 2, 3, 4]) + 100)

[101 102 103 104]


In [32]:
matrixA = np.array([[1, 2, 3], [4, 5, 6]]) + np.array([100, 200, 300])
print(matrixA)

[[101 202 303]
 [104 205 306]]


In [34]:
a = np.random.rand(5)

In [35]:
print(a)

[ 0.91516074  0.09434404  0.71916366  0.92030496  0.17254964]


In [36]:
print(a.shape)

(5,)


In [37]:
print(a.T)

[ 0.91516074  0.09434404  0.71916366  0.92030496  0.17254964]


In [38]:
print(np.dot(a, a.T))

2.24035094752


In [39]:
a = np.random.rand(5,1)

In [40]:
print(a)

[[ 0.137352  ]
 [ 0.83277899]
 [ 0.69084935]
 [ 0.65453233]
 [ 0.07977121]]


In [41]:
print(a.T)

[[ 0.137352    0.83277899  0.69084935  0.65453233  0.07977121]]


In [43]:
print(a.shape)

(5, 1)


In [44]:
print(np.dot(a, a.T))

[[ 0.01886557  0.11438386  0.09488954  0.08990132  0.01095673]
 [ 0.11438386  0.69352084  0.57532482  0.54508077  0.06643179]
 [ 0.09488954  0.57532482  0.47727282  0.45218324  0.05510989]
 [ 0.08990132  0.54508077  0.45218324  0.42841257  0.05221284]
 [ 0.01095673  0.06643179  0.05510989  0.05221284  0.00636345]]


In [45]:
print(np.random.rand(1,5))

[[ 0.22610434  0.32113428  0.51351292  0.96131191  0.39187686]]


In [46]:
print(np.random.rand(5,1))

[[ 0.58778898]
 [ 0.73122598]
 [ 0.47591448]
 [ 0.26937727]
 [ 0.97265296]]


In [47]:
assert(a.shape == (5,1))

In [48]:
print(a.reshape(5,1))

[[ 0.137352  ]
 [ 0.83277899]
 [ 0.69084935]
 [ 0.65453233]
 [ 0.07977121]]


In [49]:
print(a.reshape(1,5))

[[ 0.137352    0.83277899  0.69084935  0.65453233  0.07977121]]


In [52]:
a = np.random.randn(2,3)
b = np.random.randn(2,1)
c = a + b
print(c.shape)

(2, 3)


In [54]:
a = np.random.randn(4,3)
b = np.random.randn(3,2)
c = a * b
print(c.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [55]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print(c.shape)

(12288, 45)


In [64]:
a = np.random.randn(3,4)
b = np.random.randn(4,1)
c = np.random.randn(4,4)

for i in range(3):
  for j in range(4):
    c[i][j] = a[i][j] + b[j]
print(c)
# print(a + b)
print(a + b.T)
print(a.T + b)
# print(a.T + b.T)

[[-0.13002493 -1.04780104 -0.99701344 -1.36361845]
 [ 1.70006932 -0.45921418 -1.16444209 -0.27125967]
 [ 0.08362799 -1.71640814 -0.48299823 -1.18885382]
 [-0.7639016   1.1220122   1.49213389 -1.00752988]]
[[-0.13002493 -1.04780104 -0.99701344 -1.36361845]
 [ 1.70006932 -0.45921418 -1.16444209 -0.27125967]
 [ 0.08362799 -1.71640814 -0.48299823 -1.18885382]]
[[-0.13002493  1.70006932  0.08362799]
 [-1.04780104 -0.45921418 -1.71640814]
 [-0.99701344 -1.16444209 -0.48299823]
 [-1.36361845 -0.27125967 -1.18885382]]


In [65]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c)

[[ 1.25499668  0.8652367  -0.78099018]
 [-1.91452264  1.23040933  0.01704284]
 [-0.03739605 -0.00385022 -0.00463426]]


In [66]:
u = a * b
v = a * c
w = b + c
J = u + v - w = a * b + a * c - (b + c) = ab + ac - b - c = 
a(b + c) - (b + c) = (b + c) * (a - 1)

SyntaxError: invalid syntax (<ipython-input-66-02c62fa16279>, line 4)

In [67]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

In [77]:
print(image.shape[0])
print(image.shape[1])
print(image.shape[2])
v = image.reshape((image.shape[0]*image.shape[1], image.shape[2]))

print(v)

3
3
2
[[ 0.67826139  0.29380381]
 [ 0.90714982  0.52835647]
 [ 0.4215251   0.45017551]
 [ 0.92814219  0.96677647]
 [ 0.85304703  0.52351845]
 [ 0.19981397  0.27417313]
 [ 0.60659855  0.00533165]
 [ 0.10820313  0.49978937]
 [ 0.34144279  0.94630077]]
